config/routes.rb
BP::Application.routes.draw do
  root :to => 'admin#index'
  get '/modal/:id' => 'admin#modal', :as => 'modal'
  get '/reset/:id' => 'admin#reset', :as => 'reset'
  get '/staffs/:id/password' => 'admin#password', :as => 'password'
  post '/staffs/:id/password' => 'admin#change_password', :as => 'change_password'
  get '/login' => 'sessions#new', :as => 'signin'
  post '/login' => 'sessions#create', :as => 'signedin'
  get '/logout' => 'sessions#destroy', :as => 'signout'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(staff)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    staff ||= Staff.new
    can :read, :all
    if staff.decorate.admin?
        can :manage, :all        
    else
        can :manage, Staff, :staff_id => staff.id
    end
  end
end

app/models/salon.rb
class Salon < ActiveRecord::Base
  self.table_name ='T_SALON'
  self.primary_key = 'salon_id'
  has_many :staffs, class_name: 'Staff', foreign_key: 'salon_id'
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  self.table_name ='T_STAFF'
  self.primary_key = 'staff_id'

  belongs_to :salon, class_name: 'Salon', foreign_key: 'salon_id'
  paginates_per 50

 
end

app/controllers/admin_controller.rb
require 'string'
class AdminController < ApplicationController
  include AdminConcern

  def index
    search params, StaffQuery
  end

  def password
    render_password_view params, StaffQuery
  end

  def change_password
    do_change_password ChangeStaffPassword, StaffQuery, SavePassword, password_params, params, flash
  end
  
  def modal
    show_modal StaffQuery, params
  end

  def reset
    reset_ipad StaffQuery, ResetStaffToken, params, flash
  end

  private
  def password_params
    params.require(:staffs).permit(:password)
  end
  def errors
    @errors ||= []
  end
  helper_method :errors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationConcern
  private
  def set_locale
    I18n.locale = params[:locale] || 'ja'
  end
  def require_signin!
    if current_user.nil?
      #flash[:error] =
       #I18n.t 'application.require_signin.error'
      redirect_to signin_path
    else
      if current_user.one_time_secret.nil? and cookies[current_user.id.to_s]
        session[:staff_id] = nil
        redirect_to signin_path
      end
    end
  end
  helper_method :require_signin!
  def current_user
    @current_staff ||= StaffQuery.find session[:staff_id] if session[:staff_id]
  end
  helper_method :current_user

  def require_cookies!
    if cookies[:test_session].to_s == ''
      cookies[:test_session] = 'testing'
      if params[:cookies_enabled].nil?
        redirect_to :controller => params[:controller],
                    :action => params[:action],
                    :cookies_enabled => 'testing'
      else
        render :text => '<html><body>You need cookies</body></html>'
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsConcern
  
  def new
    render_login current_user
  end

  def create
    login SignIn, params, cookies, session, flash
  end

  def destroy    
    logout session, flash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h3><%= t('admin.index.welcome') + "  " + current_user.staff_name %></h3>
<%= link_to t('admin.index.logout'), signout_path %>
<% if flash.keys.any? %>
  <% [:success, :notice, :error].each do |t| %>
    <%= flash[t] %>
  <% end %>
<% end %>
	<div class="well">
      <form class="form-inline" role="form" action="<%= root_path %>" method="GET">
        <div class="form-group">
          <select class="form-control" name="q[role_id_eq]">
            <%= options_for_select([['管理者', 100], ['利用者', 102]], @role_id) %>
          </select>
        </div>



        <div class="form-group">
          <div class="input-group">
            <label class="sr-only" for="q_staff_name_cont">Email address</label>

            <input type="text" class="form-control" id="q_staff_name_cont" name="q[staff_name_cont]" placeholder="Name" value="<%= @staff_name %>"></input>
          </div>
        </div>
        <div class="form-group">
          <label class="sr-only" for="q_mail_address_cont">Password</label>
          <input type="text" class="form-control" id="q_mail_address_cont" name="q[mail_address_cont]" placeholder="Mail" value="<%= @mail_address %>"></input>
        </div>
        <button type="submit" class="btn btn-default search_button"><span class="glyphicon glyphicon-search " aria-hidden="true"></span></button>
        <a href="/" class="btn btn-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
        <% if params[:q].present? %>
          <label><%= t("admin.index.search_result_label") %>:</label>
          <label class="badge"><%= @staffs.count %></label>
        <% end %>
      </form>
    </div>



      <%= paginate @staffs, :theme => 'twitter-bootstrap-3' %>

     



      <table class="table table-striped table-bordered">
        <tr class="title_table">
          <td style="width: 10%;"><strong >所属店舗</strong></td>
          <td style="width: 20%;"><strong>スタッフ名</strong></td>
          <td style="width: 20%;"><strong>メールアドレス</strong></td>
          <td style="width: 20%;"><strong>パスワー</strong></td>
          <td style="width: 20%;"><strong>ipad</strong></td>
          <td class="sr-only" style="width: 10%;">#</td>
        </tr>
        <% @staffs.each_with_index do |staff, index| %>
	        <tr>
	          <td><%= staff.salon.nil? ? '': staff.salon.salon_name %></td>
	          <td><%= staff.staff_name %></td>
	          <td><%= staff.mail_address %></td>
	          <td>  
            <% if can? :manage, staff %>              
              <%= link_to password_path(staff.id), :class => "cp#{staff.id.to_s} btn btn-primary" do %>
	              <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
                <span class="glyphicon-class">Password</span>
	            <% end %>
            <% end %>
	          </td>
	          <td>
              <% if can? :manage, staff %>              
	            <a type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal" href="<%= modal_path(staff) %>">
	              <span class="glyphicon glyphicon-phone" aria-hidden="true"></span><br>
	            </a>
              <% end %>
	          </td>
	          <td>  
	            <button type="button" class="btn btn-default">
	              <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span><br>
	            </button>
	          </td>
	        </tr>
	    <% end %>
     </table>
     <!-- Modal -->
      <div class="modal fade custom" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
           <div class="modal-content">
           </div>
        </div>
      </div>

app/views/admin/modal.html.erb
            
          
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4 class="modal-title" id="myModalLabel"><strong>iPadリセット　利用者名：</strong></h4>
</div>
<div class="modal-body">
  <p>iPadリセット　利用者名：
  リセットボタンを押下すると、<br/>
  現在登録されているiPadの情報をリセットします。
  リセット後、新しいiPadでログインすると
  そのiPadからでのみログイン可能になり
</p>
</div>
<div class="modal-footer">
  <a type="button" class="btn btn-default" data-dismiss="modal">キャンセル</a>
  <a type="button" class="btn btn-primary"  href="<%= reset_path(@staff) %>">リセッ</a>
</div>

app/views/admin/password.html.erb
      
      <div class="col-md-3 well">
        <ul class="form-group" role="menu">
          <li role="presentation"><%= link_to t("admin.password.back"), root_path %></li>
          <li role="presentation"><%= link_to t("admin.password.logout"), signout_path %></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Something else here</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>
        </ul>
      </div>
      
      
      <div class="col-md-9">
        <form class="form-inline" role="form" >
          <h1><%= t("admin.password.title") %>: <%= @staff.staff_name %></h1>
        </form>
        <table class="table table-striped table-bordered">
          <tr>
            <td style="width: 50%;"  class="title_table"><strong >所属店舗</strong></td>
            <td style="width: 50%;">スタッフ名</td>

          </tr>

          <tr>
            <td  class="title_table"><strong>test</strong></td>
            <td>nonono</td>

          </tr>
          <tr>
            <td  class="title_table"><strong>test</strong></td>
            <td>nonono</td>

          </tr>
          <tr>
            <td  class="title_table"><strong>test</strong></td>
            <td>nonono</td>

          </tr>
        </table>

        <%= form_tag change_password_path(@staff), method:"POST" do %>
          <div style="display:none">
            <input type="password"/>
          </div>
          <div class="form-inline">
            <div class="form-group">
              <label><h1><%= t("admin.password.password_label") %>:</h1> </label>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" id="password" name="staffs[password]" placeholder="パスワード"></input>
            </div>
            <div class="form-group">
              <button onclick="gen_pass()" type="button" name="generate" class="btn btn-primary"><%= t("admin.password.generate_label") %></button>
            </div>
            <% if flash[:success] or flash[:danger] %>
            
            <% [:success, :danger].each do |t| %>
            <div class="alert alert-<%= t  %>" role="alert">
              <% if flash[t] %>
                <%= flash[t] %>
              <% end %>
            <% end %>
            <% if errors.count > 0 %>
                <ul>
                  <% errors.each do |error| %>
                    <li><%= error.message %></li>
                  <% end %>
                </ul>            
            <% end %>
            </div>
            <% end %>
          <div class="form-group">
            <input type="submit" name="save" class="btn btn-primary" value="<%= t("admin.password.save_label") %>"></input>
          </div>
          <div class="form-group">
            <button onclick="show_pass()" type="button" name="show" class="btn btn-sm btn-warning"><%= t("admin.password.show_label") %></button>

            <button onclick="hide_pass()" type="button" name="hide" class="btn btn-sm btn-danger" ><%= t("admin.password.hide_label") %></button>
          </div>
        <% end %>
        




<script>
      
      
      function gen_pass()
      {
        
        o = "A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z".split(',');
        var p = new Array();
        for (i = 0; i < 3; i++)
        {
          var k = getRandomInt(0, o.length);
          p[i] = o[k];
        }




        o2 = "0,1,2,3,4,5,6,7,8,9".split(',');
        var p2 = new Array();
        for (i = 0; i < 3; i++)
        {
          var k = getRandomInt(0, o2.length);
          p2[i] = o2[k];
        }




        var o3 = ['~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '|', '}', '{', '\\'];
        var p3 = new Array();
        for (i = 0; i < 2; i++)
        {
          var k = getRandomInt(0, o3.length);
          p3[i] = o3[k];
        };


        var pass = p.concat(p2).concat(p3);
        pass_shuffle = shuffle(pass);
       
        document.getElementById("password").value = pass_shuffle.join("")
        show_pass();
      }




      function getRandomInt(min, max) {
        return Math.floor(Math.random() * (max - min)) + min;
      }



      function shuffle(array) {
        var currentIndex = array.length, temporaryValue, randomIndex;

        // While there remain elements to shuffle...
        while (0 !== currentIndex) {

          // Pick a remaining element...
          randomIndex = Math.floor(Math.random() * currentIndex);
          currentIndex -= 1;

          // And swap it with the current element.
          temporaryValue = array[currentIndex];
          array[currentIndex] = array[randomIndex];
          array[randomIndex] = temporaryValue;
        }

        return array;
      }
      
      function show_pass(){
      
          document.getElementById("password").type = "text";
       
      }
       function hide_pass(){
        
       
          document.getElementById("password").type = "password";
        
      }


    </script>


        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("application.header") %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "bootstrap.min", :media => "all" %>
  <%= stylesheet_link_tag    params[:controller], :media => "all" %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "bootstrap.min" %>  
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>

</body>
</html>